### PR TITLE
Update to v0.2.0

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@jakirkham, have you seen the circleci error before?

`cmake: error while loading shared libraries: libarchive.so.13: cannot open shared object file: No such file or directory`

**Comment by jakirkham** [comment]
So please merge PR ( https://github.com/conda-forge/python-symengine-feedstock/pull/5 ) first. This actually should fix a lot of things including this `cmake` problem. Once merged please rebase these changes on top of `master`. Please let me know if you have more issues.

**Comment by isuruf** [comment]
Tests pass. Merging

**Comment by isuruf** [comment]
@jakirkham, thanks for the help

**Pull request merged**
